# University of Toronto paper by Samuel Lambert et al.
# Via: https://humantfs.ccbr.utoronto.ca/
# Downloaded URL: https://humantfs.ccbr.utoronto.ca/download/v_1.01/DatabaseExtract_v_1.01.csv
# Post-processing:
# - Manually filtered by `Is TF?` == `Yes`
# - Changed DUX1_HUMAN and DUX3_HUMAN to empty string (no Ensembl ID).
- data_file: Toronto.csv
  columns:
    Ensembl ID: EnsemblGene
    HGNC symbol: GeneSymbol

# SCENIC https://scenic.aertslab.org/
# Downloaded URL: https://resources.aertslab.org/cistarget/tf_lists/allTFs_hg38.txt
- data_file: SCENIC.tsv
  has_header: false
  columns:
    0: GeneSymbol
